### ISSUE TITLE
Dynamically change the input/output folders?

### ISSUE THREAD

**Issue by BenHaanstra** [hedrergudene/asr-sd-pipeline#1]
I tried to reach out to the creator directly on linkedin but not possible due to privacy :)

I find this repo very interesting and found many similarities in setup to what we got, but we want to expand the code to work with <any> number of containers (or different storage acc), and the issue we run into is to dynamically change the output folder in an Azure ML pipeline.

E.g. I got 5 customers, each with their own container, and for each of them I want to keep their data in their own respective containers. Ideally, I can just invoke a pipeline job with a different input/output folder, but it seems as the pipeline is defined you have to instantiate the inputs/outputs folders already, rather than that it can be changed on invoke as a parameter to the pipeline.

Any tips for addressing this?

**Comment by hedrergudene** [comment]
Hi Ben, as far as I understand, you can set up containers/folders by just modifying the config file from each of your client(s). On the other hand, you can always make use of custom datastores to perfectly suit up your data.
