### ISSUE TITLE
 MSDD inference() got an unexpected keyword argument 'input_transcriptions'

### ISSUE THREAD

**Issue by BenHaanstra** [hedrergudene/asr-sd-pipeline#3]
It seems the input_transcriptions in the main.py is not defined in the YAML (asr-sd-pipeline/components/diarize_inference/diarize_inference.yaml)

Adding
input_transcriptions:
    type: uri_folder
    optional: false

will work

**Comment by hedrergudene** [comment]
Thanks for your reported issues!
